BROWSER   = "Chrome"
URL       = "https://automationplayground.com/crm/"
LOGIN   = "admin@robotframeworktutorial.com"
PWD =   "pwd"
EmailAddress= "papis@gmail.com"
FirstName="Papis"
LastName  = "Ndoye"
City ="Dakar"
State ="Alaska"
Gender ="female"
HomeTitle="Customers Are Priority One!"

AddCustomerBtnId = "new-customer"
AddCustomerTitle = "Add Customer"
EMPTY_EMAIL = ""
EMPTY_PASSWORD = ""
